/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resident;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class residentPaymentView extends javax.swing.JFrame {

    /**
     * Creates new form residentPaymentView
     */
    public residentPaymentView() {
        initComponents();

        try {

            BufferedReader br = new BufferedReader(new FileReader("src/textFiles/residentPayment.txt"));
            Object[] Lines = br.lines().toArray();
            int i = 0;
            int paymentid = 0;
            for (i = 1; i < Lines.length; i++) {
                String line = Lines[i].toString().trim();
                String[] row = line.split(",");
                paymentid = Integer.parseInt(row[0]);
            }
            int paymentID = paymentid + 1;
            FileWriter writer = new FileWriter("src/textFiles/residentPayment.txt", true);
            writer.write(paymentID + "," + userid + "," + unitno + "," + paymenttype + "," + amount + "\n");
            writer.close();
            JOptionPane.showMessageDialog(null, "Your receipt will be generated soon!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error generating receipt!");
        }

        String tempFile = "src/textFiles/invoicetemp.txt";
        File oldFile = new File(filepath);
        File newFile = new File(tempFile);
        String field = "";
        String InvoiceID = "";
        String UserID = "";
        String UnitNo = "";
        String PaymentType = "";
        String Amount = "";
        String DueDate = "";

        try {
            FileWriter rd = new FileWriter(tempFile, false);
            BufferedWriter bw = new BufferedWriter(rd);
            PrintWriter pw = new PrintWriter(bw);
            Scanner x = new Scanner(new File(filepath));
            x.useDelimiter("[,\n]");

            while (x.hasNext()) {
                InvoiceID = x.next();
                UserID = x.next();
                UnitNo = x.next();
                PaymentType = x.next();
                Amount = x.next();
                DueDate = x.next();

                if (invoiceid.equals(InvoiceID)) {
                    pw.println(invoiceid + "," + UserID + "," + UnitNo + "," + PaymentType + "," + money + "," + DueDate);
                } else {
                    pw.println(InvoiceID + "," + UserID + "," + UnitNo + "," + PaymentType + "," + Amount + "," + DueDate);
                }
            }
            x.close();
            pw.flush();
            pw.close();
            Scanner y = new Scanner(new File(tempFile));
            FileWriter fw = new FileWriter(filepath, false);
            BufferedWriter bb = new BufferedWriter(fw);
            PrintWriter pp = new PrintWriter(bb);

            while (y.hasNext()) {
                pp.println(y.next());
            }
            y.close();
            pp.flush();
            pp.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error...");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice ID", "User ID", "Unit No", "Payment Type", "Amount (RM)", "Due Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("View all payment receipts");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice ID", "User ID", "Unit No", "Payment Type", "Amount (RM)", "Due Date"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(177, 177, 177))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedRowIndex = jTable1.getSelectedRow();

        disInvoiceID.setText(model.getValueAt(selectedRowIndex, 0).toString());
        disUserID.setText(model.getValueAt(selectedRowIndex, 1).toString());
        disUnitNo.setText(model.getValueAt(selectedRowIndex, 2).toString());
        disPaymentType.setText(model.getValueAt(selectedRowIndex, 3).toString());
        totalamount.setText(model.getValueAt(selectedRowIndex, 4).toString());
        disDueDate.setText(model.getValueAt(selectedRowIndex, 5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedRowIndex = jTable1.getSelectedRow();

        disInvoiceID.setText(model.getValueAt(selectedRowIndex, 0).toString());
        disUserID.setText(model.getValueAt(selectedRowIndex, 1).toString());
        disUnitNo.setText(model.getValueAt(selectedRowIndex, 2).toString());
        disPaymentType.setText(model.getValueAt(selectedRowIndex, 3).toString());
        totalamount.setText(model.getValueAt(selectedRowIndex, 4).toString());
        disDueDate.setText(model.getValueAt(selectedRowIndex, 5).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(residentPaymentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(residentPaymentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(residentPaymentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(residentPaymentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new residentPaymentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
